version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 17.8.0
        commands:
          - npm install -g pnpm && \
          - ''
          - pnpm -v && \
          - ''
          - pnpm install && \
          - ''
          - pnpm run docs:build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./src/.vuepress/dist
        strategy: {}
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID:
          ID: 腾讯云
          hostID:
            - 5d3c2503-eaca-4bd9-87a7-0e47447b531c
        deployArtifact:
          - source: build
            name: output
            target: ~/gitee_workflow
            dependArtifact: BUILD_ARTIFACT
        script:
          - '# 功能：部署脚本会在部署主机组的每台机器上执行'
          - '# 使用场景：先将制品包解压缩到指定目录中，再执行启动脚本deploy.sh，脚本示例地址：https://gitee.com/gitee-go/spring-boot-maven-deploy-case/blob/master/deploy.sh'
          - '# mkdir -p /home/admin/app'
          - '# tar zxvf ~/gitee_go/deploy/output.tar.gz -C /home/admin/app'
          - '# sh /home/admin/app/deploy.sh restart'
          - '# 如果你是php之类的无需制品包的制品方式，可以使用 git clone 或者 git pull 将源代码更新到服务器，再执行其他命令'
          - '# git clone ***@***.git'
          - '#echo ''Hello Gitee Go!'''
          - tar -zxvf /root/gitee_workflow/output.tar.gz -C /root/gitee_workflow/
          - cp /root/gitee_workflow/dist/* /root/gitee_workflow/blog/
          - yes | cp -r /root/gitee_workflow/dist/* /root/gitee_workflow/blog/
          - cd /root/gitee_workflow/blog
          - git add .
          - git commit -m "gitee_workflow"
          - git push origin "gh_pages"
          - rm -rf /root/gitee_workflow/dist
          - rm -rf /root/gitee_workflow/output.tar.gz
          - echo 'Hello Gitee Go! finish'
          - ''
        notify: []
        strategy:
          retry: '0'
        dependsOn: build_nodejs
